name = "Buffers"
uuid = "d9ae4b7f-d04c-4b7f-92f7-4d9c2e17e1a4"
authors = ["Daniel Kats <d.kats@fkf.mpg.de>"]
version = "0.1.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
